name: AquaCare Backend CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

# Add permissions block
permissions:
  contents: write
  pull-requests: write

env:
  NODE_VERSION: '18.18'
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run ESLint
        run: npx eslint "src/**/*.js"
        
      - name: Format and check code with Prettier
        run: |
          npx prettier --write "src/**/*.js"
          npx prettier --check "src/**/*.js"
          
      - name: Commit format changes
        if: github.event_name == 'push'
        run: |
          git config --local user.email "btimurlangit@gmail.com"
          git config --local user.name "Bintang Timurlangit"
          git add -A
          git diff-index --quiet HEAD || git commit -m "style: format code with prettier"
          git push

  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run npm audit
        run: npm audit
        
      - name: Run Snyk security scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'AquaCare Backend'
          path: '.'
          format: 'HTML'
          
  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: [code-quality, security-scan]
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: aquacare_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Generate Prisma Client
        run: npx prisma generate
        
      - name: Run database migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: "mysql://root:rootpassword@localhost:3306/aquacare_test"
          
      - name: Run tests with coverage
        run: npm test -- --coverage
        env:
          DATABASE_URL: "mysql://root:rootpassword@localhost:3306/aquacare_test"
          JWT_SECRET: "your-jwt-secret"
          
      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}